### ISSUE TITLE
Raspberry pi compatability

### ISSUE THREAD

**Issue by squidsirymchenry** [code-iai/pico_flexx_driver#24]
Is it possible to make this compatible with the Raspberry pi?

**Comment by mintar** [comment]
It should work! See #15 .

**Comment by simonePasi** [comment]
I installed pico_flexx_driver on raspberry pi 3b+ with ubuntu 16.04.

Pico_flexx_driver compiles correctly but when I launch "roslaunch pico_flexx_driver pico_flexx_driver.launch" the following error arises:

*** Error in `/opt/ros/kinetic/lib/nodelet/nodelet': malloc(): memory corruption: 0x76b117d3 ***
[FATAL] [1587564330.836949089]: Failed to load nodelet '/pico_flexx_driver` of type `pico_flexx_driver/pico_flexx_nodelet` to manager `pico_flexx'

I used libroyale-3.23.0.86-LINUX-arm-32Bit as "uname -m" gives me "armv7l"

How can I solve this error?

**Comment by mintar** [comment]
You seem to be having the same problem as the other people in #15, so please continue the discussion there. People seem to have some luck with adding `-O3` to the compiler flags. If that doesn't help, please contact pmd for support. Since the bug seems to be in their closed source part of the code, we can't do anything about it.
